version: "3.3"
services:
  codeanalysis:
    build:
      context: ./CodeAnalysis
    volumes:
      - .:/code
    ports:
    - "5001:5000"
  ml:
    build:
      context: ./MachineLearning
    volumes:
      - .:/code
    ports:
      - "5002:5000"
