version: "3.3"
services:
  detectionsystem:
    build:
      context: ./App
    stdin_open: true
    tty: true        
    depends_on:
      - codeanalysis
      - ml
    volumes:
      - .:/code
    ports:
      - "5000:5000"

  codeanalysis:
    build:
      context: ./CodeAnalysis
    volumes:
      - .:/code
    ports:
      - "5001:5000"

  ml:
    build:
      context: ./MachineLearning
    volumes:
      - .:/code
    ports:
      - "5002:5000"